repos:
  - repo: local
    hooks:
      - id: delete-bak-files
        name: Delete .bak files before commit
        entry: bash -c 'rm -f data_files/backups/*.bak'
        language: system
        always_run: true
        pass_filenames: false
